[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

# Do not draw Undiscovered sprite above Abnormalities
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/card_draw.lua"]'
pattern = "if not self.config.center.discovered and (self.ability.consumeable or self.config.center.unlocked) and not self.config.center.demo and not self.bypass_discovery_center then"
position = "after"
payload = "if not (self.ability.set == \"Joker\" and self.config.center.abno) then"
match_indent = true

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/card_draw.lua"]'
pattern = "if self.ability.name == 'Invisible Joker' and (self.config.center.discovered or self.bypass_discovery_center) then"
position = "before"
payload = "end"
match_indent = true