[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

# Create the thread
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "load_channel = love.thread.getChannel('load_channel')"
position = "after"
payload = "conductor = love.thread.getChannel('conductor')"
match_indent = true

[[patches]]
[patches.pattern]
target = "engine/sound_manager.lua"
pattern = "LOAD_CHANNEL = love.thread.getChannel('load_channel')"
position = "after"
payload = "CONDUCTOR = love.thread.getChannel('conductor')"
match_indent = true