[manifest]
version = "1.0.0"
dump_lua = true
priority = 10

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "set_profile_progress()"
position = "before"
payload = '''
-- [LobotomyCorp] Global variables stuff
self.lobc_global_modifiers = {
    "laetitia_gift",
    "price_of_silence_amplified",
    "plague_doctor_baptism",
    "child_galaxy_pebble",
}

self.lobc_global_meltdowns = {
    "malkuth",
    "yesod",
    "hod",
    "netzach",
    "tiphereth",
    "gebura",
    "chesed",
    "binah",
    "hokma",
    "day_47",
    "day_48",
    "day_49"
}

local modifiers_atlas = self.ASSET_ATLAS["lobc_LobotomyCorp_modifiers"]
self.lobc_shared_modifiers = {
    laetitia_gift = Sprite(0, 0, self.CARD_W, self.CARD_H, modifiers_atlas, {x = 0, y = 0}),
    price_of_silence_amplified = Sprite(0, 0, self.CARD_W, self.CARD_H, modifiers_atlas, {x = 1, y = 0}),
    plague_doctor_baptism = Sprite(0, 0, self.CARD_W, self.CARD_H, modifiers_atlas, {x = 2, y = 0}),
    child_galaxy_pebble = Sprite(0, 0, self.CARD_W, self.CARD_H, modifiers_atlas, {x = 3, y = 0}),
}

-- Late patches
G.UIDEF.card_h_popup = lobc_card_h_popup'''
match_indent = true